project 'SignalR.Client.ObjC Example.pbxproj'
workspace '../SignalR.Client.ObjC.xcworkspace'

target "OS X Example" do
    use_frameworks!
    platform :osx, '10.9'

    pod 'SignalR-ObjC', :path => '..'
end

target "iOS Example" do
    use_frameworks!
    platform :ios, '11.0'
    
    pod 'SignalR-ObjC', :path => '..'
end
